#/bin/sh

# Get ERP.UNO

git clone git@github.com:erpuno/abac
git clone git@github.com:erpuno/acc
git clone git@github.com:erpuno/acquire
git clone git@github.com:erpuno/act
git clone git@github.com:erpuno/addr
git clone git@github.com:erpuno/agent
git clone git@github.com:erpuno/asic
git clone git@github.com:erpuno/barlix
git clone git@github.com:erpuno/bench
git clone git@github.com:erpuno/cart
git clone git@github.com:erpuno/chat
git clone git@github.com:erpuno/cipherarch
git clone git@github.com:erpuno/crm
git clone git@github.com:erpuno/dec
git clone git@github.com:erpuno/docx
git clone git@github.com:erpuno/ecsv
git clone git@github.com:erpuno/emv
git clone git@github.com:erpuno/erp.uno
git clone git@github.com:erpuno/etf
git clone git@github.com:erpuno/exo
git clone git@github.com:erpuno/fin
git clone git@github.com:erpuno/fix
git clone git@github.com:erpuno/frontend
git clone git@github.com:erpuno/ft
git clone git@github.com:erpuno/iban
git clone git@github.com:erpuno/iot
git clone git@github.com:erpuno/jrz
git clone git@github.com:erpuno/koatuu
git clone git@github.com:erpuno/ldap
git clone git@github.com:erpuno/mach
git clone git@github.com:erpuno/mq
git clone git@github.com:erpuno/nitro
git clone git@github.com:erpuno/ocr
git clone git@github.com:erpuno/office
#git clone git@github.com:erpuno/opn
git clone git@github.com:erpuno/pay
git clone git@github.com:erpuno/plm
git clone git@github.com:erpuno/pm
git clone git@github.com:erpuno/pop3
git clone git@github.com:erpuno/rete
git clone git@github.com:erpuno/sample
git clone git@github.com:erpuno/schema
git clone git@github.com:erpuno/scm
git clone git@github.com:erpuno/sevovv
git clone git@github.com:erpuno/skyline
git clone git@github.com:erpuno/smtp
git clone git@github.com:erpuno/soa
git clone git@github.com:erpuno/sql
git clone git@github.com:erpuno/tender
git clone git@github.com:erpuno/tms
git clone git@github.com:erpuno/trade
git clone git@github.com:erpuno/unzr
git clone git@github.com:erpuno/upl
git clone git@github.com:erpuno/wms
git clone git@github.com:erpuno/ws
git clone git@github.com:erpuno/xa
