#/bin/sh

git clone git@github.com:synrc/a64
git clone git@github.com:synrc/active
git clone git@github.com:synrc/avz
git clone git@github.com:synrc/azure-crm
git clone git@github.com:synrc/base
git clone git@github.com:synrc/bpe
git clone git@github.com:synrc/ca
git clone git@github.com:synrc/chat
git clone git@github.com:synrc/cr
git clone git@github.com:synrc/crm-pro
git clone git@github.com:synrc/erz-crm
git clone git@github.com:synrc/exe
git clone git@github.com:synrc/form
git clone git@github.com:synrc/fs
git clone git@github.com:synrc/kvs
git clone git@github.com:synrc/mad
git clone git@github.com:synrc/n2o
git clone git@github.com:synrc/n2o.cloud
git clone git@github.com:synrc/n2o.dev
git clone git@github.com:synrc/nitro
git clone git@github.com:synrc/ns
git clone git@github.com:synrc/rest
git clone git@github.com:synrc/review
git clone git@github.com:synrc/rpc
git clone git@github.com:synrc/rt
git clone git@github.com:synrc/sample
git clone git@github.com:synrc/shen
git clone git@github.com:synrc/svg
git clone git@github.com:synrc/vm
